import pandas as pd

df = pd.read_csv('EcommercePurchases')
print('Ecommerce purchases exercises!')
print('Check head of df:')
print(df.head())
print()
print('How many rows and columns are there?')
print(df.info())
print()
print('What is the average purchase price?')
print(df['Purchase Price'].mean())
print()
print('What were the highest and lowest Purchase Prices?')
print('Highest: {value}'.format(value=df['Purchase Price'].max()))
print('Lowest: {value}'.format(value=df['Purchase Price'].min()))
print()
print('How many people have English as their language of choice on website?')
print(df[df['Language']=='en'].count())
print()
print('How many people have the job title of lawyer?')
print(df[df['Job']=='Lawyer'].count())
print()
print('** How many people made the purchase during the AM and how many people made the purchase during PM ? **')
print(df['AM or PM'].value_counts())
print()
print('what are the 5 most common job titles?')
print(df.groupby('Job')['Job'].count().sort_values(ascending=False).head(5))
print()
print('** Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction? **')
print(df[df['Lot']=='90 WT']['Purchase Price'])
print()
print('** What is the email of the person with the following Credit Card Number: 4926535242672853 **')
print(df[df['Credit Card']==4926535242672853]['Email'])
print()
print('** How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**')
print(df[(df['CC Provider']=='American Express') & (df['Purchase Price'] > 95)].count())
print()
print('** Hard: How many people have a credit card that expires in 2025? **')
print(sum(df['CC Exp Date'].apply(lambda x: x[3:]) == '25'))
print()
print('** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **')
print(df['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5))
print()
