import pandas as pd

df = pd.read_csv('Salaries.csv')
print(df.head())
print()
print(df.info())
print()
print('**What is the average BasePay ?**')
print(df['BasePay'].mean())
print()
print('** What is the highest amount of OvertimePay in the dataset ? **')
print(df['OvertimePay'].max())
print()
print('** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesnt match up (there is also a lowercase Joseph Driscoll). **')
print(df[df['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle'])
print()
print('** How much does JOSEPH DRISCOLL make (including benefits)? **')
print(df[df['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits'])
print()
print('** What is the name of highest paid person (including benefits)?**')
print(df[df['TotalPayBenefits']==df['TotalPayBenefits'].max()]['EmployeeName'])
print()
print('** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**')
print(df[df['TotalPayBenefits']==df['TotalPayBenefits'].min()]['EmployeeName'])
print()
print('** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **')
print(df.groupby('Year')['BasePay'].mean())
print()
print('** How many unique job titles are there? **')
print(df['JobTitle'].nunique())
print()
print('** What are the top 5 most common jobs? **')
print(df.groupby('JobTitle')['JobTitle'].count().sort_values(ascending=False).head(5))
print()
print('** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **')
print(sum(df[df['Year']==2013]['JobTitle'].value_counts() == 1))
print()
print('** How many people have the word Chief in their job title? (This is pretty tricky) **')
jobs = df['JobTitle'].tolist()
chiefs = list(filter(lambda x: 'CHIEF' in x.upper(), jobs))
print(len(chiefs))
